-- MySQL Script generated by MySQL Workbench
-- Mon Dec 24 20:50:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projectDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projectDB` ;

-- -----------------------------------------------------
-- Schema projectDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectDB` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `projectDB` ;

-- -----------------------------------------------------
-- Table `projectDB`.`Πακέτα`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectDB`.`Πακέτα` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `projectDB`.`Πακέτα` (
  `Φροντιστήρια_id` INT NOT NULL,
  `field` ENUM('Ανθρωπιστικής', 'Θετικής', 'Υγείας', 'Οικονομίας και Πληροφορικής') NOT NULL DEFAULT 'general purpose' COMMENT 'Η κατεύθυνση του μαθήματος',
  `price` SMALLINT UNSIGNED NOT NULL COMMENT 'Η τιμή του συγκεκριμένου πακέτου μαθημάτων',
  `city` VARCHAR(45) NOT NULL COMMENT 'Η πόλη του φροντιστηρίου-πακέτου',
  `street` VARCHAR(45) NOT NULL COMMENT 'Ο δρόμος του φροντιστηρίου-πακέτου',
  `street_number` SMALLINT NOT NULL COMMENT 'Ο αριθμός οδού του φροντιστηρίου-πακέτου',
  `description` MEDIUMTEXT NULL DEFAULT 'No description available',
  CONSTRAINT `fk_Μάθηματα_Φροντιστήρια`
    FOREIGN KEY (`Φροντιστήρια_id`)
    REFERENCES `projectDB`.`Φροντιστήρια` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Μάθηματα_Φροντιστήρια_idx` ON `projectDB`.`Πακέτα` (`Φροντιστήρια_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `projectDB`.`Φροντιστήρια`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectDB`.`Φροντιστήρια` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `projectDB`.`Φροντιστήρια` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Το id του κάθε φροντιστηρίου ξεχώριστα. Αυξάνεται αυτόματα με κάθε εισαγωγή.',
  `name` VARCHAR(45) NOT NULL DEFAULT 'No name' COMMENT 'Το όνομα του φροντιστηρίου',
  `description` NCHAR NULL DEFAULT 'No description available' COMMENT 'Περιγραφή τοης φροντιστηριακής μονάδας.',
  `signup_datetime` DATETIME NULL COMMENT 'Η ημερομηνία κι ώρα εγγραφής ενός φροντιστηρίου',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `projectDB`.`Φροντιστήρια` (`name` ASC) VISIBLE;

SHOW WARNINGS;
USE `projectDB` ;

-- -----------------------------------------------------
-- Placeholder table for view `projectDB`.`Αθήνα_Υγείας_τιμές`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDB`.`Αθήνα_Υγείας_τιμές` (`id` INT);
SHOW WARNINGS;

-- -----------------------------------------------------
-- View `projectDB`.`Αθήνα_Υγείας_τιμές`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectDB`.`Αθήνα_Υγείας_τιμές`;
SHOW WARNINGS;
DROP VIEW IF EXISTS `projectDB`.`Αθήνα_Υγείας_τιμές` ;
SHOW WARNINGS;
USE `projectDB`;
CREATE  OR REPLACE VIEW `Αθήνα_Υγείας_τιμές` AS
SELECT Φροντιστήρια.name AS Φροντιστήριο, Διευθύνσεις.street AS Street, 
Διευθύνσεις.street_number AS Αριθμός Οδού, Πακέτα.price AS Τιμή
FROM Φροντιστήρια NATURAL JOIN Διευθύνσεις NATURAL JOIN Πακέτα
WHERE Διευθύνσεις.city = 'Athens' AND Πακέτα.field = 'Υγείας΄;
SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `projectDB`.`Πακέτα`
-- -----------------------------------------------------
START TRANSACTION;
USE `projectDB`;
INSERT INTO `projectDB`.`Πακέτα` (`Φροντιστήρια_id`, `field`, `price`, `city`, `street`, `street_number`, `description`) VALUES (0, 'Υγείας', 200, 'Αθήνα', 'Κυψέλης', 22, 'μαθήματα υγείας');
INSERT INTO `projectDB`.`Πακέτα` (`Φροντιστήρια_id`, `field`, `price`, `city`, `street`, `street_number`, `description`) VALUES (0, 'Θετική', 250, 'Αθήνα', 'Κυψέλης', 24, 'μαθήματα θετικής');
INSERT INTO `projectDB`.`Πακέτα` (`Φροντιστήρια_id`, `field`, `price`, `city`, `street`, `street_number`, `description`) VALUES (1, 'Θετική', 300, 'Αθήνα', 'Δεληγιάννη', 3, NULL);
INSERT INTO `projectDB`.`Πακέτα` (`Φροντιστήρια_id`, `field`, `price`, `city`, `street`, `street_number`, `description`) VALUES (1, 'Υγείας', 300, 'Αθήνα', 'Πανόρμου', 55, NULL);
INSERT INTO `projectDB`.`Πακέτα` (`Φροντιστήρια_id`, `field`, `price`, `city`, `street`, `street_number`, `description`) VALUES (1, 'Ανθρωπιστικής', 320, 'Αθήνα', 'Σαρανταπόρου', 17, NULL);
INSERT INTO `projectDB`.`Πακέτα` (`Φροντιστήρια_id`, `field`, `price`, `city`, `street`, `street_number`, `description`) VALUES (1, 'Οικονομίας και Πληροφορικής', 280, 'Αθήνα', 'Ελικώνος', 88, NULL);
INSERT INTO `projectDB`.`Πακέτα` (`Φροντιστήρια_id`, `field`, `price`, `city`, `street`, `street_number`, `description`) VALUES (2, 'Ανθρωπιστικής', 200, 'Λάρισα', 'Μιαούλη', 15, NULL);
INSERT INTO `projectDB`.`Πακέτα` (`Φροντιστήρια_id`, `field`, `price`, `city`, `street`, `street_number`, `description`) VALUES (3, 'Θετικής', 450, 'Θεσσαλονίκη', 'Ευρυβιάδου', 10, NULL);
INSERT INTO `projectDB`.`Πακέτα` (`Φροντιστήρια_id`, `field`, `price`, `city`, `street`, `street_number`, `description`) VALUES (3, 'Οικονομίας και Πληροφορικής', 400, 'Θεσσαλονίκη', 'Αγίας Τριάδος', 11, NULL);
INSERT INTO `projectDB`.`Πακέτα` (`Φροντιστήρια_id`, `field`, `price`, `city`, `street`, `street_number`, `description`) VALUES (4, 'Θετικής', 600, 'Πάτρα', 'Πηγάσου', 33, NULL);
INSERT INTO `projectDB`.`Πακέτα` (`Φροντιστήρια_id`, `field`, `price`, `city`, `street`, `street_number`, `description`) VALUES (4, 'Ανθρωπιστικής', 550, 'Πάτρα', 'Πηγάσου', 33, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `projectDB`.`Φροντιστήρια`
-- -----------------------------------------------------
START TRANSACTION;
USE `projectDB`;
INSERT INTO `projectDB`.`Φροντιστήρια` (`id`, `name`, `description`, `signup_datetime`) VALUES (0, 'Φροντ0', 'Περ0', 'CURRENT_TIMESTAMP()');
INSERT INTO `projectDB`.`Φροντιστήρια` (`id`, `name`, `description`, `signup_datetime`) VALUES (1, 'Φροντ1', 'Περ1', 'CURRENT_TIMESTAMP()');
INSERT INTO `projectDB`.`Φροντιστήρια` (`id`, `name`, `description`, `signup_datetime`) VALUES (2, 'Φροντ2', 'Περ2', 'CURRENT_TIMESTAMP()');
INSERT INTO `projectDB`.`Φροντιστήρια` (`id`, `name`, `description`, `signup_datetime`) VALUES (3, 'Φροντ3', 'Περ3', 'CURRENT_TIMESTAMP()');
INSERT INTO `projectDB`.`Φροντιστήρια` (`id`, `name`, `description`, `signup_datetime`) VALUES (4, 'Φροντ4', 'Περ4', 'CURRENT_TIMESTAMP()');

COMMIT;

